env: "local" # dev, prod
token_ttl: 1h
grpc:
  port: 44040
  timeout: 2m
auth_providers:
  google:
    client_id: ""
    client_secret: ""
    redirect_url: ""
  yandex:
    client_id: ""
    client_secret: ""
    redirect_url: ""
